# Generated by Django 4.0.2 on 2022-04-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
